[build]
  publish = "dist"
  command = "bun install && bun run build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/shakespeare"
  to = "https://www.shakespeareswords.com/ajax/AjaxResponder.aspx"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
