// VCE Essential Words — edit freely. Each key is the Shakespearean form (lowercase).
// forms[0] is the primary display; subsequent entries are tap-to-cycle alternates.
// vce_note removed temporarily — shakespeareswords.com definitions show in its place.

export const ESSENTIALS = {
  naught:    { forms: ['naught', 'nothing'] },
  nothing:   { forms: ['nothing', 'naught'] },
  thee:      { forms: ['thee', 'thou', 'ye'] },
  thou:      { forms: ['thou', 'thee'] },
  thy:       { forms: ['thy', 'thine'] },
  art:       { forms: ['art', 'be'] },
  hath:      { forms: ['hath', 'has'] },
  doth:      { forms: ['doth', 'does'] },
  wilt:      { forms: ['wilt', 'wouldst'] },
  shalt:     { forms: ['shalt', 'shall'] },
  dost:      { forms: ['dost', 'do'] },
  wouldst:   { forms: ['wouldst', 'would'] },
  canst:     { forms: ['canst', 'can'] },
  mayst:     { forms: ['mayst', 'may'] },
  wast:      { forms: ['wast', 'were'] },
  ere:       { forms: ['ere', 'before'] },
  hark:      { forms: ['hark', 'hearken'] },
  hearken:   { forms: ['hearken', 'hark', 'listen'] },
  unto:      { forms: ['unto', 'to'] },
  desire:    { forms: ['desire', 'wish', 'want'] },
  wherefore: { forms: ['wherefore', 'why'] },
  perchance: { forms: ['perchance', 'perhaps'] },
  verily:    { forms: ['verily', 'truly', 'indeed'] },
  avaunt:    { forms: ['avaunt', 'away'] },
  hence:     { forms: ['hence', 'away'] },
  nay:       { forms: ['nay', 'no'] },
  yea:       { forms: ['yea', 'yes'] },
  prithee:   { forms: ['prithee', 'please'] },
  fie:       { forms: ['fie'] },
  methinks:  { forms: ['methinks', 'I think'] },
  alas:      { forms: ['alas'] },
  forsooth:  { forms: ['forsooth', 'in truth'] },
  marry:     { forms: ['marry', 'indeed'] },
  anon:      { forms: ['anon', 'soon'] },
  withal:    { forms: ['withal', 'moreover'] },
  sirrah:    { forms: ['sirrah'] },
  sith:      { forms: ['sith', 'since'] },
  oft:       { forms: ['oft', 'often'] },
  sovereign: { forms: ['sovereign', 'king'] },
  liege:     { forms: ['liege', 'lord'] },
  storm:     { forms: ['storm', 'tempest'] },
  thunder:   { forms: ['thunder'] },
  rage:      { forms: ['rage', 'fury'] },
  fortune:   { forms: ['fortune', 'fate'] },
  nature:    { forms: ['nature', 'natural'] },
  mad:       { forms: ['mad', 'crazed'] },
  poor:      { forms: ['poor'] },
  good:      { forms: ['good', 'goodly'] },
  well:      { forms: ['well'] },
}

export const MADNESS = new Set([
  'tempest', 'storm', 'winds', 'hurricano', 'cataract',
  'rage', 'madly', 'crack', 'thunder', 'dreadful', 'shaked', 'fury',
])
