// VCE Essential Words — edit freely. Each key is the Shakespearean form (lowercase).
// forms[0] is the primary display; subsequent entries are tap-to-cycle alternates.

export const ESSENTIALS = {
  naught:    { forms: ['naught', 'nothing'],           vce_note: 'Lear\'s descent uses "naught" to signal both emptiness and madness — the reduction of a king to zero. "Nothing will come of nothing."' },
  nothing:   { forms: ['nothing', 'naught'],           vce_note: 'The play\'s most loaded word. Cordelia\'s "Nothing, my lord" triggers the entire catastrophe. Nothingness is Lear\'s fate.' },
  thee:      { forms: ['thee', 'thou', 'ye'],          vce_note: 'Intimate second-person pronoun. Lear\'s "thee" to Cordelia signals familial bond; to the Fool, shared vulnerability in madness.' },
  thou:      { forms: ['thou', 'thee'],                vce_note: 'Intimate or condescending address. Lear\'s "thou"s to the storm mark his break from courtly register into raw humanity.' },
  thy:       { forms: ['thy', 'thine'],                vce_note: 'Possessive of "thou" — intimate ownership. "Thy youngest daughter does not love thee least" — Kent\'s truth to power.' },
  art:       { forms: ['art', 'be'],                   vce_note: '"Art" (are). "Who art thou?" — recognition and identity are central to Lear\'s tragic journey of self-knowledge.' },
  hath:      { forms: ['hath', 'has'],                 vce_note: '"Hath" (has). "He hath ever but slenderly known himself" — Kent\'s devastating prophecy of Lear\'s fatal flaw.' },
  doth:      { forms: ['doth', 'does'],                vce_note: '"Doth" (does). Formal third-person auxiliary. "Doth Lear walk thus?" marks the fall from sovereign to wanderer.' },
  wilt:      { forms: ['wilt', 'wouldst'],             vce_note: '"Wilt" (will). "Wilt thou forgive?" — second-person future drives the reconciliation arc between Lear and Cordelia.' },
  shalt:     { forms: ['shalt', 'shall'],              vce_note: '"Shalt" (shall). Prophetic weight. "Thou shalt find that I\'ll resume the shape which thou dost think I have cast off for ever."' },
  dost:      { forms: ['dost', 'do'],                  vce_note: '"Dost" (do/does). "Dost thou know me?" — recognition scenes central to the play\'s theme of identity and perception.' },
  wouldst:   { forms: ['wouldst', 'would'],            vce_note: '"Wouldst" (would). Conditional desire — the language of what might have been. Central to the tragic structure of regret.' },
  canst:     { forms: ['canst', 'can'],                vce_note: '"Canst" (can). Capability interrogation. "Canst thou blame him?" — moral questioning woven through VCE analytical themes.' },
  mayst:     { forms: ['mayst', 'may'],                vce_note: '"Mayst" (may). Granting permission or expressing possibility. Marks moments of trust tentatively extended.' },
  wast:      { forms: ['wast', 'were'],                vce_note: '"Wast" (were). Past tense of "be". "What wast thou?" — identity stripped bare in the storm\'s truth-telling.' },
  ere:       { forms: ['ere', 'before'],               vce_note: '"Ere" (before). Temporal urgency. "Ere I was old" frames Lear\'s lament on age, wisdom, and what was surrendered.' },
  hark:      { forms: ['hark', 'hearken'],             vce_note: '"Hark" (listen). Command form marking key revelations. The Fool uses it to pull Lear\'s attention toward truth he refuses to hear.' },
  wherefore: { forms: ['wherefore', 'why'],            vce_note: '"Wherefore" (why — cause, not location). Demands explanation. Lear\'s "Wherefore should I stand here?" is a crisis of self-examination.' },
  perchance: { forms: ['perchance', 'perhaps'],        vce_note: '"Perchance" (perhaps). Introduces uncertainty into a world of false certainty. Key to the play\'s preoccupation with fortune and chance.' },
  verily:    { forms: ['verily', 'truly', 'indeed'],   vce_note: '"Verily" (truly). Oath-like emphasis. Marks truth-telling in a play structurally built on deception and flattery.' },
  avaunt:    { forms: ['avaunt', 'away'],              vce_note: '"Avaunt" (away — violent). Lear\'s "Avaunt!" to Goneril signals the first irrevocable break in familial loyalty.' },
  hence:     { forms: ['hence', 'away'],               vce_note: '"Hence" (go away from here). Lear\'s banishments — of Kent, of Cordelia — drive the entire plot. Language as violence.' },
  nay:       { forms: ['nay', 'no'],                   vce_note: '"Nay" (no). Stark refusal. Cordelia\'s "Nay" in the love-test is arguably the most consequential syllable in the play.' },
  yea:       { forms: ['yea', 'yes'],                  vce_note: '"Yea" (yes). Formal affirmation. Contrasted with Cordelia\'s honest "nay" against the court\'s performative "yea".' },
  prithee:   { forms: ['prithee', 'please'],           vce_note: '"Prithee" (pray thee — please). The Fool uses it to soften unbearable truths, making Lear receptive to wisdom through intimacy.' },
  fie:       { forms: ['fie'],                         vce_note: '"Fie" — exclamation of moral disgust. Marks ethical outrage at betrayal. A one-syllable verdict on wickedness.' },
  methinks:  { forms: ['methinks', 'I think'],         vce_note: '"Methinks" (it seems to me). Signals subjective, fallible perception — critical when characters catastrophically misread reality.' },
  alas:      { forms: ['alas'],                        vce_note: '"Alas" — pure lament. Cordelia\'s "Alas" anchors the play\'s emotional pivot points. Grief without rhetorical decoration.' },
  forsooth:  { forms: ['forsooth', 'in truth'],        vce_note: '"Forsooth" (in truth). An oath of sincerity — often ironic when spoken by flattering characters who mean the opposite.' },
  marry:     { forms: ['marry', 'indeed'],             vce_note: '"Marry" (mild oath, from Virgin Mary). The Fool uses it to ease into truths Lear cannot hear directly. Softened clarity.' },
  anon:      { forms: ['anon', 'soon'],                vce_note: '"Anon" (soon, shortly). Temporal urgency. Reflects the play\'s catastrophic pace — events arrive before Lear can comprehend them.' },
  withal:    { forms: ['withal', 'moreover'],          vce_note: '"Withal" (with that, moreover). Stacking argument — appears in the Fool\'s riddling cumulative speeches. Logic as trap.' },
  sirrah:    { forms: ['sirrah'],                      vce_note: '"Sirrah" — dismissive address to social inferiors. When Lear uses it to the Fool, it ironically reveals his own diminished status.' },
  sith:      { forms: ['sith', 'since'],               vce_note: '"Sith" (since — causal). Marks reason and consequence. Key to the play\'s tragic logic: every cause unfurls catastrophic effect.' },
  oft:       { forms: ['oft', 'often'],                vce_note: '"Oft" (often). "How oft the sight of means to do ill deeds / Makes ill deeds done" — compacted moral observation.' },
  sovereign: { forms: ['sovereign', 'king'],           vce_note: '"Sovereign" — the play interrogates sovereignty itself. What does kingship mean when a king surrenders power willingly?' },
  liege:     { forms: ['liege', 'lord'],               vce_note: '"Liege" — feudal address. Marks the hierarchical world Lear shatters by dividing his kingdom. Language carrying a lost order.' },
  storm:     { forms: ['storm', 'tempest'],            vce_note: '"Storm" — Act 3\'s central symbol. The external storm mirrors Lear\'s internal collapse and the unravelling of natural order.' },
  thunder:   { forms: ['thunder'],                     vce_note: '"Thunder" — divine indifference. Lear commands the thunder as though still king: his delusion at its most naked and human.' },
  rage:      { forms: ['rage', 'fury'],                vce_note: '"Rage" — Lear\'s defining emotion. His rage against daughters, against the storm, against fate structures the entire tragedy.' },
  fortune:   { forms: ['fortune', 'fate'],             vce_note: '"Fortune" — Shakespeare\'s personified chance. The wheel of Fortune turns indiscriminately for all in Lear\'s world.' },
  nature:    { forms: ['nature', 'natural'],           vce_note: '"Nature" — Edmund\'s amoral "goddess Nature" vs Lear\'s hierarchical natural order. Two incompatible philosophies in collision.' },
  mad:       { forms: ['mad', 'crazed'],               vce_note: '"Mad" — the play dissolves the boundary between madness and wisdom. Lear\'s madness yields insight; Edgar\'s feigned madness, survival.' },
  poor:      { forms: ['poor'],                        vce_note: '"Poor" — "Poor naked wretches" marks Lear\'s moral awakening on the heath: empathy born from dispossession.' },
  good:      { forms: ['good', 'goodly'],              vce_note: '"Good" — morally and socially loaded. The truly "good" characters (Cordelia, Kent) are exiled. Goodness is punished in Lear.' },
  well:      { forms: ['well'],                        vce_note: '"Well" — Lear\'s reluctant "Well, well, well" signals the concessive acknowledgement of harsh truths he can no longer refuse.' },
}

export const MADNESS = new Set([
  'tempest', 'storm', 'winds', 'hurricano', 'cataract',
  'rage', 'madly', 'crack', 'thunder', 'dreadful', 'shaked', 'fury',
])
